"""Pydantic models shared by the API for chat and game interactions."""
from __future__ import annotations

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Represents a single turn in the chat conversation."""

    role: Literal["user", "assistant", "system"] = Field(
        ..., description="Role of the speaker sending the message."
    )
    content: str = Field(..., description="Natural language content of the message.")


class ConversationRequest(BaseModel):
    """Request body for the conversation endpoint."""

    messages: List[ChatMessage] = Field(
        ..., description="Ordered history of the conversation with the assistant."
    )


class ConversationResponse(BaseModel):
    """Response payload returned after generating a chat completion."""

    reply: str = Field(..., description="Message generated by Gemma 2.")


class CreateSessionRequest(BaseModel):
    """Request body used to instantiate a new retro game session."""

    game_id: str = Field(..., description="Identifier of the ROM to launch.")
    mode: Literal["solo", "coop"] = Field(
        "solo", description="Gameplay mode determining player/AI participation."
    )
    description_prompt: Optional[str] = Field(
        None,
        description=(
            "Optional text appended to the observation summary before sending it to "
            "Gemma 2."
        ),
    )


class SessionResponse(BaseModel):
    """Response describing an active emulator session."""

    session_id: str = Field(..., description="Unique identifier of the session.")
    game_id: str = Field(..., description="Identifier of the ROM launched in this session.")
    mode: Literal["solo", "coop"]


class StepRequest(BaseModel):
    """Request payload to advance the game one step."""

    player_action: Optional[str] = Field(
        None,
        description="Action provided by the human player, if any, expressed as a label.",
    )
    use_ai: bool = Field(
        False,
        description="Whether Gemma 2 should be queried to determine the action.",
    )


class StepResponse(BaseModel):
    """Response returned after advancing the emulator state."""

    observation: str = Field(
        ..., description="Textual summary of the observation returned to the frontend."
    )
    action_taken: str = Field(
        ..., description="Action label executed by the environment during the step."
    )
    reward: float = Field(..., description="Reward value returned by the environment.")
    done: bool = Field(
        ..., description="Whether the episode has ended after executing the action."
    )
    info: dict = Field(..., description="Additional info dictionary from the environment.")


class SaveStateResponse(BaseModel):
    """Response payload returned after saving or loading a state."""

    success: bool = Field(..., description="Whether the operation completed successfully.")
    path: Optional[str] = Field(None, description="File path of the save state.")


class LoadStateRequest(BaseModel):
    """Request body to load an emulator state from disk."""

    path: str = Field(..., description="Path to the state file to load.")
